version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: ads_db
      POSTGRES_USER: ads_user
      POSTGRES_PASSWORD: ads_password
    ports:
      - "5431:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
